from __future__ import annotations

STATE_SENATE_WIKIPEDIA_SOURCES: list[dict[str, str]] = [
    {"state": "Alabama", "source_url": "https://en.wikipedia.org/wiki/Alabama_Senate"},
    {"state": "Alaska", "source_url": "https://en.wikipedia.org/wiki/Alaska_Senate"},
    {"state": "Arizona", "source_url": "https://en.wikipedia.org/wiki/Arizona_State_Senate"},
    {"state": "Arkansas", "source_url": "https://en.wikipedia.org/wiki/Arkansas_Senate"},
    {"state": "California", "source_url": "https://en.wikipedia.org/wiki/California_State_Senate"},
    {"state": "Colorado", "source_url": "https://en.wikipedia.org/wiki/Colorado_Senate"},
    {"state": "Connecticut", "source_url": "https://en.wikipedia.org/wiki/Connecticut_State_Senate"},
    {"state": "Delaware", "source_url": "https://en.wikipedia.org/wiki/Delaware_Senate"},
    {"state": "Florida", "source_url": "https://en.wikipedia.org/wiki/Florida_Senate"},
    {"state": "Georgia", "source_url": "https://en.wikipedia.org/wiki/Georgia_State_Senate"},
    {"state": "Hawaii", "source_url": "https://en.wikipedia.org/wiki/Hawaii_Senate"},
    {"state": "Idaho", "source_url": "https://en.wikipedia.org/wiki/Idaho_Senate"},
    {"state": "Illinois", "source_url": "https://en.wikipedia.org/wiki/Illinois_Senate"},
    {"state": "Indiana", "source_url": "https://en.wikipedia.org/wiki/Indiana_Senate"},
    {"state": "Iowa", "source_url": "https://en.wikipedia.org/wiki/Iowa_Senate"},
    {"state": "Kansas", "source_url": "https://en.wikipedia.org/wiki/Kansas_Senate"},
    {"state": "Kentucky", "source_url": "https://en.wikipedia.org/wiki/Kentucky_Senate"},
    {"state": "Louisiana", "source_url": "https://en.wikipedia.org/wiki/Louisiana_State_Senate"},
    {"state": "Maine", "source_url": "https://en.wikipedia.org/wiki/Maine_Senate"},
    {"state": "Maryland", "source_url": "https://en.wikipedia.org/wiki/Maryland_Senate"},
    {"state": "Massachusetts", "source_url": "https://en.wikipedia.org/wiki/Massachusetts_Senate"},
    {"state": "Michigan", "source_url": "https://en.wikipedia.org/wiki/Michigan_Senate"},
    {"state": "Minnesota", "source_url": "https://en.wikipedia.org/wiki/Minnesota_Senate"},
    {"state": "Mississippi", "source_url": "https://en.wikipedia.org/wiki/Mississippi_Senate"},
    {"state": "Missouri", "source_url": "https://en.wikipedia.org/wiki/Missouri_Senate"},
    {"state": "Montana", "source_url": "https://en.wikipedia.org/wiki/Montana_Senate"},
    {"state": "Nevada", "source_url": "https://en.wikipedia.org/wiki/Nevada_Senate"},
    {"state": "New Hampshire", "source_url": "https://en.wikipedia.org/wiki/New_Hampshire_Senate"},
    {"state": "New Jersey", "source_url": "https://en.wikipedia.org/wiki/New_Jersey_Senate"},
    {"state": "New Mexico", "source_url": "https://en.wikipedia.org/wiki/New_Mexico_Senate"},
    {"state": "New York", "source_url": "https://en.wikipedia.org/wiki/New_York_State_Senate"},
    {"state": "North Carolina", "source_url": "https://en.wikipedia.org/wiki/North_Carolina_Senate"},
    {"state": "North Dakota", "source_url": "https://en.wikipedia.org/wiki/North_Dakota_Senate"},
    {"state": "Ohio", "source_url": "https://en.wikipedia.org/wiki/Ohio_Senate"},
    {"state": "Oklahoma", "source_url": "https://en.wikipedia.org/wiki/Oklahoma_Senate"},
    {"state": "Oregon", "source_url": "https://en.wikipedia.org/wiki/Oregon_State_Senate"},
    {"state": "Pennsylvania", "source_url": "https://en.wikipedia.org/wiki/Pennsylvania_State_Senate"},
    {"state": "Rhode Island", "source_url": "https://en.wikipedia.org/wiki/Rhode_Island_Senate"},
    {"state": "South Carolina", "source_url": "https://en.wikipedia.org/wiki/South_Carolina_Senate"},
    {"state": "South Dakota", "source_url": "https://en.wikipedia.org/wiki/South_Dakota_Senate"},
    {"state": "Tennessee", "source_url": "https://en.wikipedia.org/wiki/Tennessee_Senate"},
    {"state": "Texas", "source_url": "https://en.wikipedia.org/wiki/Texas_Senate"},
    {"state": "Utah", "source_url": "https://en.wikipedia.org/wiki/Utah_State_Senate"},
    {"state": "Vermont", "source_url": "https://en.wikipedia.org/wiki/Vermont_Senate"},
    {"state": "Virginia", "source_url": "https://en.wikipedia.org/wiki/Virginia_Senate"},
    {"state": "Washington", "source_url": "https://en.wikipedia.org/wiki/Washington_State_Senate"},
    {"state": "West Virginia", "source_url": "https://en.wikipedia.org/wiki/West_Virginia_Senate"},
    {"state": "Wisconsin", "source_url": "https://en.wikipedia.org/wiki/Wisconsin_Senate"},
    {"state": "Wyoming", "source_url": "https://en.wikipedia.org/wiki/Wyoming_Senate"},
]

STATE_HOUSE_WIKIPEDIA_SOURCES: list[dict[str, str]] = [
    {"state": "Alabama", "source_url": "https://en.wikipedia.org/wiki/Alabama_House_of_Representatives", "office_name": "Alabama House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Alaska", "source_url": "https://en.wikipedia.org/wiki/Alaska_House_of_Representatives", "office_name": "Alaska House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Arizona", "source_url": "https://en.wikipedia.org/wiki/Arizona_House_of_Representatives", "office_name": "Arizona House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Arkansas", "source_url": "https://en.wikipedia.org/wiki/Arkansas_House_of_Representatives", "office_name": "Arkansas House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "California", "source_url": "https://en.wikipedia.org/wiki/California_State_Assembly", "office_name": "California State Assembly", "role_title": "State Assemblymember", "subdepartment_name": "State Assembly", "chamber": "house"},
    {"state": "Colorado", "source_url": "https://en.wikipedia.org/wiki/Colorado_House_of_Representatives", "office_name": "Colorado House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Connecticut", "source_url": "https://en.wikipedia.org/wiki/Connecticut_House_of_Representatives", "office_name": "Connecticut House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Delaware", "source_url": "https://en.wikipedia.org/wiki/Delaware_House_of_Representatives", "office_name": "Delaware House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Florida", "source_url": "https://en.wikipedia.org/wiki/Florida_House_of_Representatives", "office_name": "Florida House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Georgia", "source_url": "https://en.wikipedia.org/wiki/Georgia_House_of_Representatives", "office_name": "Georgia House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Hawaii", "source_url": "https://en.wikipedia.org/wiki/Hawaii_House_of_Representatives", "office_name": "Hawaii House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Idaho", "source_url": "https://en.wikipedia.org/wiki/Idaho_House_of_Representatives", "office_name": "Idaho House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Illinois", "source_url": "https://en.wikipedia.org/wiki/Illinois_House_of_Representatives", "office_name": "Illinois House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Indiana", "source_url": "https://en.wikipedia.org/wiki/Indiana_House_of_Representatives", "office_name": "Indiana House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Iowa", "source_url": "https://en.wikipedia.org/wiki/Iowa_House_of_Representatives", "office_name": "Iowa House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Kansas", "source_url": "https://en.wikipedia.org/wiki/Kansas_House_of_Representatives", "office_name": "Kansas House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Kentucky", "source_url": "https://en.wikipedia.org/wiki/Kentucky_House_of_Representatives", "office_name": "Kentucky House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Louisiana", "source_url": "https://en.wikipedia.org/wiki/Louisiana_House_of_Representatives", "office_name": "Louisiana House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Maine", "source_url": "https://en.wikipedia.org/wiki/Maine_House_of_Representatives", "office_name": "Maine House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Maryland", "source_url": "https://en.wikipedia.org/wiki/Maryland_House_of_Delegates", "office_name": "Maryland House of Delegates", "role_title": "State Delegate", "subdepartment_name": "House of Delegates", "chamber": "house"},
    {"state": "Massachusetts", "source_url": "https://en.wikipedia.org/wiki/Massachusetts_House_of_Representatives", "office_name": "Massachusetts House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Michigan", "source_url": "https://en.wikipedia.org/wiki/Michigan_House_of_Representatives", "office_name": "Michigan House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Minnesota", "source_url": "https://en.wikipedia.org/wiki/Minnesota_House_of_Representatives", "office_name": "Minnesota House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Mississippi", "source_url": "https://en.wikipedia.org/wiki/Mississippi_House_of_Representatives", "office_name": "Mississippi House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Missouri", "source_url": "https://en.wikipedia.org/wiki/Missouri_House_of_Representatives", "office_name": "Missouri House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Montana", "source_url": "https://en.wikipedia.org/wiki/Montana_House_of_Representatives", "office_name": "Montana House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Nevada", "source_url": "https://en.wikipedia.org/wiki/Nevada_Assembly", "office_name": "Nevada Assembly", "role_title": "Assemblymember", "subdepartment_name": "State Assembly", "chamber": "house"},
    {"state": "New Hampshire", "source_url": "https://en.wikipedia.org/wiki/New_Hampshire_House_of_Representatives", "office_name": "New Hampshire House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "New Jersey", "source_url": "https://en.wikipedia.org/wiki/New_Jersey_General_Assembly", "office_name": "New Jersey General Assembly", "role_title": "Assemblymember", "subdepartment_name": "General Assembly", "chamber": "house"},
    {"state": "New Mexico", "source_url": "https://en.wikipedia.org/wiki/New_Mexico_House_of_Representatives", "office_name": "New Mexico House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "New York", "source_url": "https://en.wikipedia.org/wiki/New_York_State_Assembly", "office_name": "New York State Assembly", "role_title": "State Assemblymember", "subdepartment_name": "State Assembly", "chamber": "house"},
    {"state": "North Carolina", "source_url": "https://en.wikipedia.org/wiki/North_Carolina_House_of_Representatives", "office_name": "North Carolina House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "North Dakota", "source_url": "https://en.wikipedia.org/wiki/North_Dakota_House_of_Representatives", "office_name": "North Dakota House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Ohio", "source_url": "https://en.wikipedia.org/wiki/Ohio_House_of_Representatives", "office_name": "Ohio House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Oklahoma", "source_url": "https://en.wikipedia.org/wiki/Oklahoma_House_of_Representatives", "office_name": "Oklahoma House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Oregon", "source_url": "https://en.wikipedia.org/wiki/Oregon_House_of_Representatives", "office_name": "Oregon House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Pennsylvania", "source_url": "https://en.wikipedia.org/wiki/Pennsylvania_House_of_Representatives", "office_name": "Pennsylvania House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Rhode Island", "source_url": "https://en.wikipedia.org/wiki/Rhode_Island_House_of_Representatives", "office_name": "Rhode Island House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "South Carolina", "source_url": "https://en.wikipedia.org/wiki/South_Carolina_House_of_Representatives", "office_name": "South Carolina House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "South Dakota", "source_url": "https://en.wikipedia.org/wiki/South_Dakota_House_of_Representatives", "office_name": "South Dakota House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Tennessee", "source_url": "https://en.wikipedia.org/wiki/Tennessee_House_of_Representatives", "office_name": "Tennessee House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Texas", "source_url": "https://en.wikipedia.org/wiki/Texas_House_of_Representatives", "office_name": "Texas House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Utah", "source_url": "https://en.wikipedia.org/wiki/Utah_House_of_Representatives", "office_name": "Utah House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Vermont", "source_url": "https://en.wikipedia.org/wiki/Vermont_House_of_Representatives", "office_name": "Vermont House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "Virginia", "source_url": "https://en.wikipedia.org/wiki/Virginia_House_of_Delegates", "office_name": "Virginia House of Delegates", "role_title": "State Delegate", "subdepartment_name": "House of Delegates", "chamber": "house"},
    {"state": "Washington", "source_url": "https://en.wikipedia.org/wiki/Washington_House_of_Representatives", "office_name": "Washington House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
    {"state": "West Virginia", "source_url": "https://en.wikipedia.org/wiki/West_Virginia_House_of_Delegates", "office_name": "West Virginia House of Delegates", "role_title": "State Delegate", "subdepartment_name": "House of Delegates", "chamber": "house"},
    {"state": "Wisconsin", "source_url": "https://en.wikipedia.org/wiki/Wisconsin_State_Assembly", "office_name": "Wisconsin State Assembly", "role_title": "State Assemblymember", "subdepartment_name": "State Assembly", "chamber": "house"},
    {"state": "Wyoming", "source_url": "https://en.wikipedia.org/wiki/Wyoming_House_of_Representatives", "office_name": "Wyoming House of Representatives", "role_title": "State Representative", "subdepartment_name": "House of Representatives", "chamber": "house"},
]


def merge_sources(configured: list[dict[str, str]], defaults: list[dict[str, str]], state_key: str = "state") -> list[dict[str, str]]:
    merged: dict[str, dict[str, str]] = {}
    for source in defaults:
        merged[str(source[state_key])] = dict(source)
    for source in configured:
        merged[str(source[state_key])] = dict(source)
    return list(merged.values())
