from __future__ import annotations

TERRITORY_EXECUTIVE_PEOPLE: list[dict[str, str]] = [
    {
        "territory": "Puerto Rico",
        "full_name": "Jenniffer González-Colón",
        "role_title": "Governor",
        "office_name": "Governor",
        "source_url": "https://en.wikipedia.org/wiki/Jenniffer_Gonz%C3%A1lez-Col%C3%B3n",
        "parser_identity": "wikipedia_territory_executives_v1",
    },
    {
        "territory": "Guam",
        "full_name": "Lou Leon Guerrero",
        "role_title": "Governor",
        "office_name": "Governor",
        "source_url": "https://en.wikipedia.org/wiki/Lou_Leon_Guerrero",
        "parser_identity": "wikipedia_territory_executives_v1",
    },
    {
        "territory": "Guam",
        "full_name": "Josh Tenorio",
        "role_title": "Lieutenant Governor",
        "office_name": "Lieutenant Governor",
        "source_url": "https://en.wikipedia.org/wiki/Josh_Tenorio",
        "parser_identity": "wikipedia_territory_executives_v1",
    },
    {
        "territory": "U.S. Virgin Islands",
        "full_name": "Albert Bryan",
        "role_title": "Governor",
        "office_name": "Governor",
        "source_url": "https://en.wikipedia.org/wiki/Albert_Bryan",
        "parser_identity": "wikipedia_territory_executives_v1",
    },
    {
        "territory": "U.S. Virgin Islands",
        "full_name": "Tregenza Roach",
        "role_title": "Lieutenant Governor",
        "office_name": "Lieutenant Governor",
        "source_url": "https://en.wikipedia.org/wiki/Tregenza_Roach",
        "parser_identity": "wikipedia_territory_executives_v1",
    },
    {
        "territory": "Northern Mariana Islands",
        "full_name": "Arnold Palacios",
        "role_title": "Governor",
        "office_name": "Governor",
        "source_url": "https://en.wikipedia.org/wiki/Arnold_Palacios",
        "parser_identity": "wikipedia_territory_executives_v1",
    },
    {
        "territory": "Northern Mariana Islands",
        "full_name": "David Apatang",
        "role_title": "Lieutenant Governor",
        "office_name": "Lieutenant Governor",
        "source_url": "https://en.wikipedia.org/wiki/David_Apatang",
        "parser_identity": "wikipedia_territory_executives_v1",
    },
    {
        "territory": "American Samoa",
        "full_name": "Pulaali'i Nikolao Pula",
        "role_title": "Governor",
        "office_name": "Governor",
        "source_url": "https://en.wikipedia.org/wiki/Pulaali%27i_Nikolao_Pula",
        "parser_identity": "wikipedia_territory_executives_v1",
    },
]

TERRITORY_CONGRESSIONAL_PEOPLE: list[dict[str, str]] = [
    {
        "territory": "Puerto Rico",
        "full_name": "Pablo José Hernández Rivera",
        "role_title": "Resident Commissioner",
        "office_name": "Resident Commissioner",
        "source_url": "https://en.wikipedia.org/wiki/Pablo_Jos%C3%A9_Hern%C3%A1ndez_Rivera",
        "parser_identity": "wikipedia_territory_congress_v1",
    },
    {
        "territory": "Guam",
        "full_name": "James Moylan",
        "role_title": "Delegate to the U.S. House of Representatives",
        "office_name": "U.S. House of Representatives",
        "source_url": "https://en.wikipedia.org/wiki/James_Moylan",
        "parser_identity": "wikipedia_territory_congress_v1",
    },
    {
        "territory": "U.S. Virgin Islands",
        "full_name": "Stacey Plaskett",
        "role_title": "Delegate to the U.S. House of Representatives",
        "office_name": "U.S. House of Representatives",
        "source_url": "https://en.wikipedia.org/wiki/Stacey_Plaskett",
        "parser_identity": "wikipedia_territory_congress_v1",
    },
    {
        "territory": "Northern Mariana Islands",
        "full_name": "Kimberlyn King-Hinds",
        "role_title": "Delegate to the U.S. House of Representatives",
        "office_name": "U.S. House of Representatives",
        "source_url": "https://en.wikipedia.org/wiki/Kimberlyn_King-Hinds",
        "parser_identity": "wikipedia_territory_congress_v1",
    },
    {
        "territory": "American Samoa",
        "full_name": "Uifa'atali Amata",
        "role_title": "Delegate to the U.S. House of Representatives",
        "office_name": "U.S. House of Representatives",
        "source_url": "https://en.wikipedia.org/wiki/Uifa%27atali_Amata",
        "parser_identity": "wikipedia_territory_congress_v1",
    },
]

TERRITORY_LEGISLATURE_SOURCES: list[dict[str, str]] = [
    {
        "territory": "Puerto Rico",
        "source_url": "https://en.wikipedia.org/wiki/Senate_of_Puerto_Rico",
        "office_name": "Senate of Puerto Rico",
        "role_title": "Senator",
        "subdepartment_name": "Senate",
        "chamber": "senate",
    },
    {
        "territory": "Puerto Rico",
        "source_url": "https://en.wikipedia.org/wiki/House_of_Representatives_of_Puerto_Rico",
        "office_name": "House of Representatives of Puerto Rico",
        "role_title": "Representative",
        "subdepartment_name": "House of Representatives",
        "chamber": "house",
    },
    {
        "territory": "Guam",
        "source_url": "https://en.wikipedia.org/wiki/Guam_Legislature",
        "office_name": "Guam Legislature",
        "role_title": "Senator",
        "subdepartment_name": "Legislature",
        "chamber": "senate",
    },
    {
        "territory": "U.S. Virgin Islands",
        "source_url": "https://en.wikipedia.org/wiki/Legislature_of_the_Virgin_Islands",
        "office_name": "Legislature of the Virgin Islands",
        "role_title": "Senator",
        "subdepartment_name": "Legislature",
        "chamber": "senate",
    },
    {
        "territory": "Northern Mariana Islands",
        "source_url": "https://en.wikipedia.org/wiki/Northern_Mariana_Islands_Senate",
        "office_name": "Northern Mariana Islands Senate",
        "role_title": "Senator",
        "subdepartment_name": "Senate",
        "chamber": "senate",
    },
    {
        "territory": "Northern Mariana Islands",
        "source_url": "https://en.wikipedia.org/wiki/Northern_Mariana_Islands_House_of_Representatives",
        "office_name": "Northern Mariana Islands House of Representatives",
        "role_title": "Representative",
        "subdepartment_name": "House of Representatives",
        "chamber": "house",
    },
    {
        "territory": "American Samoa",
        "source_url": "https://en.wikipedia.org/wiki/American_Samoa_Senate",
        "office_name": "American Samoa Senate",
        "role_title": "Senator",
        "subdepartment_name": "Senate",
        "chamber": "senate",
    },
    {
        "territory": "American Samoa",
        "source_url": "https://en.wikipedia.org/wiki/American_Samoa_House_of_Representatives",
        "office_name": "American Samoa House of Representatives",
        "role_title": "Representative",
        "subdepartment_name": "House of Representatives",
        "chamber": "house",
    },
]
